### ISSUE TITLE
lang=cn 时报 warning: unused global option(s)

### ISSUE THREAD

**Issue by zstcode** [ElegantLaTeX/ElegantPaper#10]
导入overleaf，设置了`lang=cn` 以后，就报这个 warning

![图片](https://user-images.githubusercontent.com/17093158/56955557-5c464c00-6b74-11e9-991e-98017bb6a0b2.png)

![图片](https://user-images.githubusercontent.com/17093158/56956518-01faba80-6b77-11e9-9486-6e5a27523c9c.png)

**Comment by EthanDeng** [comment]
我们自己传了 Overleaf，修改了一点点代码（并且更新到 Github）。你可以使用我们传到 Overleaf 的[版本](https://www.overleaf.com/latex/templates?addsearch=elegantlatex)。

**Comment by zstcode** [comment]
啊原来上面有了，这个版本没问题了，谢谢
