### ISSUE TITLE
位置不够导致图片出现在下一页

### ISSUE THREAD

**Issue by EthanLifeGreat** [ElegantLaTeX/ElegantPaper#11]
正如展示的最终图，图1出现在了第三页（本应紧接着1.4节）
有什么比较便捷的方式让这张图自适应大小并紧接着原来的位置展示？

**Comment by EthanDeng** [comment]
> 正如展示的最终图，图1出现在了第三页（本应紧接着1.4节）
> 有什么比较便捷的方式让这张图自适应大小并紧接着原来的位置展示？

没有图？图片的自动浮动请参考 LaTeX 的基础书籍。
