### ISSUE TITLE
reference不显示的问题

### ISSUE THREAD

**Issue by tzjtatata** [ElegantLaTeX/ElegantPaper#14]
没有太多的提示。但是一点都没有改，从master分支直接下载的文件，elegantpaper-cn.tex编译之后就是不出reference。不知道为什么。

**Comment by EthanDeng** [comment]
你需要在 xelatex 或者 pdflatex 编译中加上参考文献编译。
比如 xelatex bibtex xelatex xelatex。

**Comment by tzjtatata** [comment]
> 你需要在 xelatex 或者 pdflatex 编译中加上参考文献编译。
> 比如 xelatex bibtex xelatex xelatex。

感谢。我在mac上试过，但是不管用。
