### ISSUE TITLE
After updated to Mac OS 10.15.1, Chinese can not be presented

### ISSUE THREAD

**Issue by zhixuanli** [ElegantLaTeX/ElegantPaper#18]
Reference:
https://zhuanlan.zhihu.com/p/90404943

You can temporarily fix this problem by typing this command in your shell:

```
ln -s /System/Library/Fonts/Supplemental/Songti.ttc /Library/Fonts
```

Do not use `cp` command, the soft link is enough

**Comment by EthanDeng** [comment]
可以根据最新版，通过使用 `chinesefont=none` 选项，然后设置系统自有字体。
