### ISSUE TITLE
如何解决相邻参考文献为相同作者默认用横线代替？

### ISSUE THREAD

**Issue by Tonywangrui** [ElegantLaTeX/ElegantPaper#19]
如何解决相邻参考文献为相同作者默认用横线代替？ 本地文件中没有.bst 文件，因模板的.bst包含在economic宏包，故网上查阅的方法不可行

**Comment by EthanDeng** [comment]
我把 `aer` 这个样式去掉了，然后改为默认 `apalike` 样式，并且提供一个选项接口：`bibstyle`，你们可以声明自己想要的参考文献样式（仅限于 `lang=en` 模式下），如果想用 `unsrt`，文类选项加上 `bibstyle=unsrt` 即可，例子：
```tex
\documentclass[11pt,en,bibstyle=unsrt]{elegantpaper}
```

样式参考：
1. [https://www.overleaf.com/learn/latex/Bibtex_bibliography_styles](https://www.overleaf.com/learn/latex/Bibtex_bibliography_styles)
2. [Comparison of bibTeX styles](http://homepage.stat.uiowa.edu/~rlenth/ALPHA/bibstylescompared.pdf)

**Comment by EthanDeng** [comment]
#4

**Comment by EthanDeng** [comment]
回到你的横线问题，你尝试改个样式吧，仍然有问题提供 MWE。

**Comment by Tonywangrui** [comment]
自己尝试后还是不行，后期我再试试如果还是不行，就给作者发MWE，非常谢谢！

**Comment by hushidong** [comment]
这个需求，既然用apa样式，其实可以用biblatex，biblatex中的apa样式是biblatex作者写的。所以什么需求都能给你实现。
可以先尝试一下，如果有什么问题也可以问我。
