### ISSUE TITLE
请问如何在中文标题摘要关键词之后加英文标题摘要关键词

### ISSUE THREAD

**Issue by aranya-source** [ElegantLaTeX/ElegantPaper#23]
如题，在之前的问题中可以添加英文摘要，但是如何在英文摘要之前再添加英文标题，作者英文信息呢？
感谢！

**Comment by aranya-source** [comment]
也就是说行文顺序是中文标题 作者中文信息 中文摘要 英文标题 作者英文信息 英文摘要 正文
感谢

**Comment by sikouhjw** [comment]
参考[如何在一个页面同时有中英文的摘要](https://wenda.latexstudio.net/q-1124.html)

**Comment by xiasummer** [comment]
还需要添加一个英文的标题

**Comment by EthanDeng** [comment]
中英文摘要请参考 #5。

英文标题在模板里面并没有现成的方法，所以只能自行构造这个。现在 `\title` 里面的格式是`\LARGE` 和 `\bfseries`，你可以使用 center 环境写一下。
