### ISSUE TITLE
无法编译，出现error

### ISSUE THREAD

**Issue by glowforyou** [ElegantLaTeX/ElegantPaper#26]
latex小白，在使用texworks运行中文模板时有如下error
![image](https://user-images.githubusercontent.com/48880825/78419123-0e37a380-7675-11ea-9228-7d73da59c728.png)
![image](https://user-images.githubusercontent.com/48880825/78419127-2f988f80-7675-11ea-85a5-9dec670ede0c.png)
但是英文版没有问题，请求帮忙看看，感谢

**Comment by EthanDeng** [comment]
根据你的提示信息，显示的是应为使用了 numbers 选项（新版才有）导致的，但是这个选项是支持的。我猜测是因为的 cls 版本是旧版的。你提供下你的版本信息。

**Comment by TheodoreSKong** [comment]
> 根据你的提示信息，显示的是应为使用了 numbers 选项（新版才有）导致的，但是这个选项是支持的。我猜测是因为的 cls 版本是旧版的。你提供下你的版本信息。

我也遇到了这个问题；盲猜是在cls里requiredPackage natbib的时候传递的参数与gbt7714.sty里引用natbib的时候传递的参数option不一致的问题；但是不知道这个问题怎么解决？

**Comment by EthanDeng** [comment]
https://github.com/ElegantLaTeX/ElegantBook/issues/92

等更新。

**Comment by EthanDeng** [comment]
已经更新修复，原因是因为 `gbt7714` 宏包更新了使用方法导致模板出现了错误，现已修复。
