### ISSUE TITLE
怎样让参考文献里的作者名字不要变成全部大写

### ISSUE THREAD

**Issue by Pipi24** [ElegantLaTeX/ElegantPaper#27]
我编译后一个参考文献格式如下

[1] BORDES A, USUNIER N, GARCIA-DURAN A, et al. Translating embeddings for modeling multi-relational data[C]//Advances in neural information processing systems. [S.l.: s.n.], 2013: 2787-2795.

作者的名字变成了全部大写的形式，请问怎样让参考文献里的作者名字只有首字母大写呢

**Comment by yzbx** [comment]
> 我编译后一个参考文献格式如下
> 
> [1] BORDES A, USUNIER N, GARCIA-DURAN A, et al. Translating embeddings for modeling multi-relational data[C]//Advances in neural information processing systems. [S.l.: s.n.], 2013: 2787-2795.
> 
> 作者的名字变成了全部大写的形式，请问怎样让参考文献里的作者名字只有首字母大写呢

这个应该在bibtex文件中更改就可以了。

**Comment by EthanDeng** [comment]
参考文献格式问题，取决于 bibstyle，不属于本模板的问题，给定 bibstyle=xxx，使用方法如下：

```tex
\documentclass[bibstyle=xxx,...]{elegantpaper}
```
