### ISSUE TITLE
如何设置页眉？

### ISSUE THREAD

**Issue by gcgeng** [ElegantLaTeX/ElegantPaper#28]
如题

**Comment by EthanDeng** [comment]
页眉设置和普通 LaTeX 页眉设置没区别，使用 fancyhdr 宏包。

**Comment by EthanDeng** [comment]
#17

**Comment by EthanDeng** [comment]
参考：
1. https://www.overleaf.com/learn/latex/headers_and_footers
2. https://ctan.org/pkg/fancyhdr
