### ISSUE TITLE
ecolor没有定义

### ISSUE THREAD

**Issue by shanhaiying** [ElegantLaTeX/ElegantPaper#3]
由于elegantpaper去除了elegantnote类中的green等颜色选项， 使得proof环境出错， 因为其引用了ecolor。 再有proofname没有与语言选项关联。

**Comment by Liam0205** [comment]
@shanhaiying 欢迎提 PR。

**Comment by EthanDeng** [comment]
已经删除了 ecolor，proofname 好了，谢谢反馈！
