### ISSUE TITLE
paper模板的页码偏右

### ISSUE THREAD

**Issue by zalois** [ElegantLaTeX/ElegantPaper#30]
感谢大佬精心制作的模板。汇报一个paper模板的小bug.
1.页码不居中。之前note模板的同样问题大佬已改正了。不知道book模板是否会有同样bug.
2.paper模板的参考文献能否去掉style设置，因为各类期刊没有统一要求。再改cls文件有点麻烦。可以让用户在文档中自己设置style也好。
感谢大佬的工作

**Comment by EthanDeng** [comment]
页码问题之前修正过，你核对下你的版本，如果有问题，需要把 `hyperref` 调到 `geometry` 宏包之前，book 和 paper 都改过，具体你可以看版本历史 https://github.com/ElegantLaTeX/ElegantPaper/compare/v0.08...master

**Comment by EthanDeng** [comment]
参考文献的 style 设置，其实你不应该去管的，工作论文的核心是内容，而且几乎没有自定义任何命令，目的就是为了让你们在换用其他模板的时候，直接换文类就行了。现在 bibstyle 可以使用其他样式，之前是固定了样式。因为根据你的描述，感觉你的版本是旧版本，你可以看下新版本。
