### ISSUE TITLE
0.09版本elegantpaper-cn无法正常编译

### ISSUE THREAD

**Issue by ChiuYuen-HSUI** [ElegantLaTeX/ElegantPaper#31]
我在编译0.09版本elegantpaper-cn时遇到了以下错误和警告：

Undefined control sequence. \setlength\parindent{2\ccwd}}}{\relax}
Extra \else. \setlength\parindent{2\ccwd}}}{\relax}
Extra \fi. \setlength\parindent{2\ccwd}}}{\relax}
Citation `en3' on page 3 undefined
No file elegantpaper-cn.bbl.
There were undefined citations.

并没有对elegantpaper-cn作任何修改，请问是哪里出bug了吗？

**Comment by EthanDeng** [comment]
需要使用 TeX Live 2020，讨论见：https://github.com/ElegantLaTeX/ElegantBook/issues/92
