### ISSUE TITLE
最多加载4页，之后的无法显示。

### ISSUE THREAD

**Issue by gsj0605** [ElegantLaTeX/ElegantPaper#32]
首先感谢作者！模板很好，准本用来当作我的翻译工作。一开始用的比较好，但是编辑了一段时间之后发现后面的输入内容无法加载。我把您的内容稍微改动了一下。加入了几个命令。例如:
\tableofcontents
\thispagestyle{empty} 
\newpage
\cleardoublepage
\setcounter{page}{1}
\clearpage 
\input{abstract}
这些，由于section太多。习惯了用这种方式书写。
但是写道第四个section的时候发现后面的都无法显示，目录原本有的内容也变成了一片空白。
这是有什么bug吗?
感谢！

**Comment by EthanDeng** [comment]
你 input 的文件里面有错误吧

**Comment by gsj0605** [comment]
> 你 input 的文件里面有错误吧

我看了一下没有错误，有一些input我还没有编辑。只是写了一些类似
\section{概要}
这样的标题。
但是目录里加载不出来内容，并且这些个input里的内容也无法显示出来呢

**Comment by Liam0205** [comment]
@gsj0605 完整的 MWE 打个包传上来看看？把与你私人工作有关的可以删掉。删掉之后再编译一遍确认可以复现问题，再传上来。

**Comment by gsj0605** [comment]
> @gsj0605 完整的 MWE 打个包传上来看看？把与你私人工作有关的可以删掉。删掉之后再编译一遍确认可以复现问题，再传上来。
你好，我刚看了一下是我其中一个input里面有问题。

**Comment by gsj0605** [comment]
> 你 input 的文件里面有错误吧

你好，我刚看了一下我其中一个input里面有问题。
