### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by wenddymacro** [ElegantLaTeX/ElegantPaper#33]
! Undefined control sequence.
<argument>  \ifXeTeX 
                     \ifdefstring {\ELEGANT@chinesefont }{founder}{ \Require...
l.132     \setlength\parindent{2\ccwd}}}{\relax}
                                                
?

**Comment by EthanDeng** [comment]
使用 TeX Live 2020 进行编译，不要使用 CTeX。

**Comment by BadeSummer** [comment]
> 使用 TeX Live 2020 进行编译，不要使用 CTeX。

使用TeX Live 2017 版本也会报这个错，所以是一定需要最近的2020版本吗？

**Comment by sikouhjw** [comment]
> 使用TeX Live 2017 版本也会报这个错，所以是一定需要最近的2020版本吗？

最好使用 TeX Live 2020
