### ISSUE TITLE
overleaf编译elegantpaper-cn.tex报错

### ISSUE THREAD

**Issue by nzh19970106** [ElegantLaTeX/ElegantPaper#34]
BibTeX Illegal, another \bibstyle command : \bibstyle : {gbt7714-author-year} 
output.aux, line 19

**Comment by sikouhjw** [comment]
用这个[https://www.overleaf.com/latex/templates/elegantpaper-template/yzghrqjhmmmr](https://www.overleaf.com/latex/templates/elegantpaper-template/yzghrqjhmmmr)，发行版要与模板匹配，Overleaf 没有升级到 texlive2020，所以用不了最新版
