### ISSUE TITLE
Error: Option clash for package natbib.

### ISSUE THREAD

**Issue by liushunyu** [ElegantLaTeX/ElegantPaper#35]
/usr/local/texlive/2020/texmf-dist/tex/latex/gbt7714/gbt7714.sty:63: LaTeX Error: Option clash for package natbib.

听说是gbt7714版本更新了导致现在不匹配？请问怎么解决？

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantBook/issues/92

**Comment by liushunyu** [comment]
> [ElegantLaTeX/ElegantBook#92](https://github.com/ElegantLaTeX/ElegantBook/issues/92)

谢谢
