### ISSUE TITLE
mac使用elegantpaper缺少字体

### ISSUE THREAD

**Issue by baker221** [ElegantLaTeX/ElegantPaper#36]
mac使用最新版mactex，warning中缺少方正字体，自行安装后也无法使用。
且mactex自带的0.8elegantpaper会报如下错误：
```
LaTeX Error: Option clash for package natbib. [\RequirePackage]
```

**Comment by sikouhjw** [comment]
> 且mactex自带的0.8elegantpaper会报如下错误：
> 
> ```
> LaTeX Error: Option clash for package natbib. [\RequirePackage]
> ```

升级全部宏包
