### ISSUE TITLE
如何更改模版默认参考文献样式，使用/bibstyle仍有一点问题

### ISSUE THREAD

**Issue by cycle95** [ElegantLaTeX/ElegantPaper#4]
使用elegantpaper作为模版，定义好documentclass之后使用 “\bibstyle{unsrt}”指定了 参考文献格式，但是编译后发现文中出现的是[1]格式的引用，但是最后参考文献的排列还是按照作者字母顺序，而不是按照unsrt样式定义的按引用顺序排列，且查看编译的.aux文件发现“\bibstyle{aer}”。

请问怎么样才能覆盖掉模版默认的参考文献样式？

**Comment by EthanDeng** [comment]
`elegantpaper.cls` 最后一句注释掉就行了，也就是下面这行：

```tex
\bibliographystyle{aer}
```

**Comment by cycle95** [comment]
> `elegantpaper.cls` 最后一句注释掉就行了，也就是下面这行：
> 
> ```
> \bibliographystyle{aer}
> ```
修改后正常了，非常感谢

**Comment by sierxue** [comment]
有个建议，能不能考虑一下？
如果电脑里面没有装 aer.bst 文件的话，用英文模板时文献显示不出来，因为没有经验，今天遇到这种情况，找了很久的原因才找出问题。
因为 aer.bst 在宏包 economic 里面，有没有可能 require 这个宏包，这样容易查找出解决办法？

**Comment by EthanDeng** [comment]
> 有个建议，能不能考虑一下？
> 如果电脑里面没有装 aer.bst 文件的话，用英文模板时文献显示不出来，因为没有经验，今天遇到这种情况，找了很久的原因才找出问题。
> 因为 aer.bst 在宏包 economic 里面，有没有可能 require 这个宏包，这样容易查找出解决办法？

参考 https://github.com/ElegantLaTeX/ElegantPaper/issues/19#issuecomment-570772369
