### ISSUE TITLE
Feature Request: 可以给文档加一个双栏模式吗

### ISSUE THREAD

**Issue by clysto** [ElegantLaTeX/ElegantPaper#41]
```tex
\documentclass[twocolumn]{elegantpaper}
```

虽然article类也有双栏模式，elegantpaper也可以将twocolumn属性正确的传递给article类，但是如果能针对elegantpaper的样式做一些针对性的优化会更加方便。

**Comment by EthanDeng** [comment]
ElegantPaper 定位是 working paper 的模板，你的想法，我考虑一下。
