### ISSUE TITLE
关于图表的标题问题

### ISSUE THREAD

**Issue by Jeffrey-huu** [ElegantLaTeX/ElegantPaper#44]
![(ZOYLTN))J`(S})4E5Y%TV3](https://user-images.githubusercontent.com/50811411/88501337-bba43d80-cffd-11ea-9405-c41dd61fd4ff.png)
如上图，在使用Elegantpaper模板写作时，老师要求图片表格标题不要黑体，我尝试过titlesec宏包和caption宏包，但是都修改失败了。

我在浏览模板的cls文件时在第81行发现如下代码：
`\RequirePackage[font=small,labelfont={bf}]{caption}`

猜测是labelfont参数对字体的设定，有没有啥方法可以在外部修改标题编号的字体，谢谢~

**Comment by sikouhjw** [comment]
提供发行版版本、模板版本和mwe

**Comment by Jeffrey-huu** [comment]
tex live2020，版本0.09，最小工作示例如下：
`\begin{figure}[htbp]
    \centering
    \includegraphics[width=15cm]{太阳高度角示意图}
    \caption{用于计算太阳高度角的天文三角形} 
    \label{solarh}
\end{figure}`

目前问题已解决，在外部使用\captionsetup命令即可重新设置格式，准备关闭issue，麻烦啦。
