### ISSUE TITLE
\figref 和 \tabref 的表述有问题

### ISSUE THREAD

**Issue by sikouhjw** [ElegantLaTeX/ElegantPaper#45]
https://github.com/ElegantLaTeX/ElegantPaper/blob/99bb48fcbdf46c06bb07a115e9464ecbf2955809/elegantpaper-cn.tex#L101-L102
应改成
```tex
\lstinline{\figref}：用法和 \lstinline{\ref} 类似，但是会在引用前添加“图”； 
```

**Comment by EthanDeng** [comment]
已修改。
