### ISSUE TITLE
标题字体和中文逗号发生改变

### ISSUE THREAD

**Issue by shujuecn** [ElegantLaTeX/ElegantPaper#46]
## 基本信息

- 系统：Mac
- 发行版：MacTeX 2020
- 模板：ElegantPaper 0.09
- 编辑器：VSCode
- 编译方式：XeLaTeX

## MWE

```LaTeX
\documentclass[lang=cn]{elegantpaper}

\title{标题字体}
\author{}
\date{\today}

\begin{document}

\maketitle

\begin{abstract}
逗号，逗号
\keywords{逗号，逗号}
\end{abstract}

\section{字体}
逗号，逗号

\end{document}
```

## 问题

1. 篇名、小标题、“摘要”、“关键词”的字体变为**华文中宋**
2. 摘要内容、正文的**中文逗号**变成不知名字体

## Warings

```
Font "FandolSong-Regular" does not contain requested
(fontspec)	Script "CJK".

Font "FandolKai-Regular" does not contain requested
(fontspec)	Script "CJK".
```

## PDF截图
![输出PDF预览](https://tva1.sinaimg.cn/large/007S8ZIlgy1gitxmrzd8aj30ma0g3my1.jpg)

**Comment by sikouhjw** [comment]
看起来是 CTeX 宏集的字体检测出问题了
工作方法：用 `\documentclass[cn, fontset = mac]{elegantpaper}`
治根方法：升级全部宏包
PS：你现在调用的是 `fandol`，不是「华文中宋」，逗号也是「中文逗号」，不过是 `FandolSong` 的中文逗号

**Comment by shujuecn** [comment]
感谢您的回复和对问题描述的更正！
我使用了`fontset = mac`选项，并使用`sudo tlmgr update --all`命令更新了宏包。
逗号的显示发生了变化，但文字的样式没有变化。
Waring:
```bash
Font "Kaiti SC" does not contain requested Script
(fontspec)	"CJK".

Font "Songti SC Light" does not contain requested
(fontspec)	Script "CJK".
```
截图如下：
![字体](https://tva1.sinaimg.cn/large/007S8ZIlgy1giu04il9ufj30y40keta3.jpg)

**Comment by sikouhjw** [comment]
字体已经改变了，因为有警告
> ```shell
> Font "Kaiti SC" does not contain requested Script
> (fontspec)	"CJK".
> 
> Font "Songti SC Light" does not contain requested
> (fontspec)	Script "CJK".
> ```
这表明已经用了 mac 的字体，只是「长的比较像，你没看出不同」，可以用 `pdffonts` 命令行工具查看字体，详情看《[工具：PDF处理的一些小技巧](https://zhuanlan.zhihu.com/p/197919733)》

**Comment by shujuecn** [comment]
看起来字体确实改变了

更新宏包前：

```bash
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
NBPJAL+FandolSong-Bold-Identity-H    CID Type 0C       Identity-H       yes yes no       5  0
NATVCG+FandolKai-Regular-Identity-H  CID Type 0C       Identity-H       yes yes no       7  0
HLGVII+TeXGyreTermesX-Regular        Type 1C           WinAnsi          yes yes yes      8  0
YIOMZF+TeXGyreTermesX-Bold           Type 1C           WinAnsi          yes yes yes      9  0
FYXSID+FandolSong-Regular-Identity-H CID Type 0C       Identity-H       yes yes no      11  0
```

更新宏包后：

```bash
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
IWTXZO+STSongti-SC-Bold              CID TrueType      Identity-H       yes yes yes      5  0
XUYMGA+STKaitiSC-Regular             CID TrueType      Identity-H       yes yes yes      7  0
YJRCJA+TeXGyreTermesX-Regular        Type 1C           WinAnsi          yes yes yes      8  0
FPOJAO+TeXGyreTermesX-Bold           Type 1C           WinAnsi          yes yes yes      9  0
SNSHQV+STSongti-SC-Light             CID TrueType      Identity-H       yes yes yes     11  0
```

那该怎么更改为模板中使用的标题字体呢？
需要仿照模板**1.4 中文字体选项**的示例自定义吗？

**Comment by sikouhjw** [comment]
> 那该怎么更改为模板中使用的标题字体呢？
> 需要仿照模板**1.4 中文字体选项**的示例自定义吗？

`elegantpaper-cn.pdf` 中，用到的字体是「中易字库」，是 CTeX 宏集在 win 下默认调用的字库，mac 中没有。
建议有三个：
- 去网上下载、安装中易字库；
- 不需要仿照模板手册的字体，就用默认的就好；
- 要追求字体效果，可以试试模板手册里写的「方正字体」。

**Comment by sikouhjw** [comment]
- 如果选择「去网上下载、安装中易字库」，只需要指定 `fontset = windows` 即可；
- 如果选择「方正字体」，只需要指定 `chinesefont = founder` 即可。

**Comment by shujuecn** [comment]
我安装了模板中建议的**方正字体**，并使用`chinesefont = founder`选项，实现了期望的显示效果。
再次感谢你的耐心指导。
截图如下：
![](https://tva1.sinaimg.cn/large/007S8ZIlgy1giu29jv2ptj30sd0i3my7.jpg)
