### ISSUE TITLE
cn.tex在macOS下编译无法显示中文

### ISSUE THREAD

**Issue by dvoprm** [ElegantLaTeX/ElegantPaper#49]
![Screen Shot 2020-10-22 at 12 06 45 AM](https://user-images.githubusercontent.com/23055579/96747192-8d66ac00-13fa-11eb-92bf-6db7d7dc05de.png)

系统：macOS 10.15.7
软件：TeXstudio 3.0.1 (git 3.0.1)
elegantpaper版本：0.09
还需要什么内容需要我贴上来？

谢谢

**Comment by sikouhjw** [comment]
https://github.com/CTeX-org/forum/issues/157

**Comment by dvoprm** [comment]
谢谢楼上，按https://github.com/CTeX-org/forum/issues/157#issuecomment-711139514 ，
问题解决。
