### ISSUE TITLE
请问如何添加中英文摘要

### ISSUE THREAD

**Issue by AlfredQuan** [ElegantLaTeX/ElegantPaper#5]
你好，这个模板非常有帮助，不过我需要在论文里同时添加中英文摘要，请问应该怎么设置？谢谢！

**Comment by EthanDeng** [comment]
本模板只添加了对应语言的摘要环境，所以需要做一些比较 tricky 的改动。下面改动为基于中文模式，添加英文摘要环境的方法，英文模式添加中文摘要环境类似。

首先，在导言区（`\begin{document}` 之前）加上

```tex
\newcommand{\ekeywords}[1]{\vskip2ex\par\noindent\normalfont{\bfseries Key Words: }#1}
```
然后在正常的 `abstract` 环境之后使用下面的命令将中文的 `摘要` 改为 `Abstract`：

```tex
\renewcommand{\abstractname}{Abstract}
```
最后在英文 Abstract  环境中，使用 `\ekeywords` 替换原先的 `\keywords` 就行了。摘要部分完整的代码为：

```tex
\begin{abstract}
% Chinese Abstract
\keywords{Elegant\LaTeX{}，工作论文，模板}
\end{abstract}

\renewcommand{\abstractname}{Abstract}

\begin{abstract}
% Enlish Abstract 
\ekeywords{Elegant\LaTeX{}, Working Paper, Template}
\end{abstract}
```

效果为下图。

![DoubleAbstract](https://user-images.githubusercontent.com/8111364/54861618-26d56400-4d67-11e9-8032-052b431c535a.png)

**Comment by AlfredQuan** [comment]
多谢大佬！

**Comment by hqg19971124** [comment]
您好，请问：（1）在插入文献时，怎样才会出现像中文论文那样的上标[1]这种情况呢？（2）怎样才能使得插入的文献在文章最后全部显示？谢谢您
