### ISSUE TITLE
Font issues in overleaf

### ISSUE THREAD

**Issue by chenqiuyuan** [ElegantLaTeX/ElegantPaper#50]
Many thanks for your elegant template :)

However, there are three warnings in the overleaf as soon as I opened the template. Could you help to solve the warning of the template?

Version: Chinese
Compiler Version: XeLatex 2019

Font "FandolSong-Regular" does not contain requested Script "CJK".
Font "FandolKai-Regular" does not contain requested Script "CJK".
Font "FandolHei-Regular" does not contain requested Script "CJK".

**Comment by sikouhjw** [comment]
https://github.com/CTeX-org/forum/issues/34 and https://zhuanlan.zhihu.com/p/145429470

**Comment by chenqiuyuan** [comment]
Thank you very much:)
