### ISSUE TITLE
请问下，参考文献的序号怎么加呢

### ISSUE THREAD

**Issue by HenryJi529** [ElegantLaTeX/ElegantPaper#52]
<img width="506" alt="截屏2021-01-08 上午7 19 05" src="https://user-images.githubusercontent.com/41288155/103955683-cbfe3e00-5181-11eb-8ccc-169c11f83416.png">

如题，想询问下，怎么在文献条目前添加类似这种【1】的序号

**Comment by EthanDeng** [comment]
使用 `cite=numbers` 选项：
```tex
\documentclass[...., cite=numbers, ...]{elegantpaper}
```
