### ISSUE TITLE
如果有两个以上的作者，且其中一个作者对应多个\institute，怎么实现呢？

### ISSUE THREAD

**Issue by liqihao2000** [ElegantLaTeX/ElegantPaper#54]

**Comment by yinxiuqu** [comment]
\author{author1\\
institute1\\
institute2}
这样可以吗？

**Comment by sikouhjw** [comment]
参考
https://github.com/ElegantLaTeX/ElegantPaper/blob/d8e407917e49cf98619405fa7cd0660f92a99a58/elegantpaper-cn.tex#L6
```tex
\author{author1 \\ institute1 \\ institute2 \and author2 \\ institute3}
```
