### ISSUE TITLE
“Illegal, another \bibstyle command“ in Ubuntu20.04

### ISSUE THREAD

**Issue by miaowuduck** [ElegantLaTeX/ElegantPaper#56]
When I use the Elegant Paper in Ubuntu 20.04 , and I clone the code and try to make a PDF by compile it XeLaTeX -> BibLaTeX -> XeLaTeX*2. But an error happened when I use the Bibtex
The error gives 
**Illegal, another \bibstyle command**
and I find in the automatically formed file "elegantpaper-cn.aux", the line 18,19 is
**\bibstyle{gbt7714-unsrt}
\bibstyle{gbt7714-author-year}**
Acturally, it's double defined.
So how can I avoid this?

**Comment by sikouhjw** [comment]
用 texlive 2021
