### ISSUE TITLE
部分字显示不出来

### ISSUE THREAD

**Issue by JingleiHuang** [ElegantLaTeX/ElegantPaper#58]
我使用：
%!TEX program = xelatex
% 完整编译: xelatex -> bibtex -> xelatex -> xelatex
\documentclass[lang=cn,12pt,a4paper,chinesefont = nofont]{elegantpaper}
作为表头，但编译时候发现“彧”字显示不出来（是框里面一个F的图标），请问如何解决呢？

**Comment by sikouhjw** [comment]
```tex
fontset=windows % win
fontset=ubuntu % overleaf
```
