### ISSUE TITLE
\nocite{*} 之后无法打印出参考文献

### ISSUE THREAD

**Issue by amenomori** [ElegantLaTeX/ElegantPaper#6]
```
\nocite{*}
\bibstyle{unsrt}
\bibliography{wpref}
```

如上使用的命令，但并未打印出参考文献。请问如何解决？

**Comment by onns** [comment]
```
\nocite{*}
\bibliographystyle{unsrt}
\bibliography{wpref}
```
换这个试试，如果还不行，就是编译的问题了。

**Comment by EthanDeng** [comment]
@AMENOMORI 由于 `elegantpaper.cls` 里面已经指定了参考文献的样式，所以用户在使用这个命令的时候会出错。你可以在 `elegantpaper.cls` 里面修改，把最后一局 `\bibliographystyle{aer}` 改为 `\bibliographystyle{unsrt}`。

**Comment by amenomori** [comment]
试过了楼上二位的方法，遗憾的是都无什么效果。以下附上日志，希望能作为解决问题的参考。

![image](https://user-images.githubusercontent.com/25379827/54998076-30312b80-5008-11e9-943f-825b6f0dac5e.png)

**Comment by onns** [comment]
因为我用的是这个模板的大概0.04版本，那时候还没有把 `\bibliographystyle{aer}` 写进cls文件，所以三楼说的才是正解。

我不知道其它编译器如何，我用的是在 Mac 下的 VS Code+MacTeX，最开始我不能显示出引用是因为我在编译过程中没有使用 `bibtex` 这个命令，而模板的第一行 `%!TEX program = xelatex` 是指定编译一次，且用 xelatex 编译。

虽然我没有办法找出你的错误，但是我很乐意将我的方法教给你，这样也能够达到一样的效果。

附上教程：[VS Code 与 MacTex](https://www.jianshu.com/p/d2c1ae324951)

**Comment by amenomori** [comment]
非常感谢二位的帮助。正如五楼所言，在单独使用 BibTeX 这个 Recipe 编译之后成功打印出了参考文献，非常感谢！

CC @EthanDeng 请关闭此 issue，非常感谢。

**Comment by EthanDeng** [comment]
额，使用 BibTeX 的话，完整的编译方式 `PDFLaTeX->BibTeX->PDFLaTeX*2` 或者 `XeLaTeX->BibTeX->XeLaTeX*2`，我觉得这个应该差不多是常识吧，直到刚看到你发的，突然想到会不会没有用 `BibTeX` 编译过.....

@AMENOMORI 你自己可以关闭的，非常感谢 @onns 的解答！

P.S. 你们回复的格式我稍微改了下，之前图和链接都挂了。
