### ISSUE TITLE
如何将英文作者名自动大写改成普通的写法?

### ISSUE THREAD

**Issue by mingchiuli** [ElegantLaTeX/ElegantPaper#60]
标准格式规定作者名全部大写，比如Thomas要写成THOMAS，但是目前的大部分人都习惯普通的写法，就是Thomas这种。标准中规定的写法反而不是主流大众常用的.

**Comment by sikouhjw** [comment]
`texdoc gbt7714`, sec7 自定义样式
```tex
  #0 'uppercase.name :=
```
