### ISSUE TITLE
overleaf缺字

### ISSUE THREAD

**Issue by papayaistrash** [ElegantLaTeX/ElegantPaper#61]
嗨，我在使用的時候，發現部分繁體常用的字有少字的現象，舉例來說，「叡」這個字就是缺少的，
請問要如何解決？

使用平台：overleaf

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantPaper/issues/58

**Comment by papayaistrash** [comment]
另外，如果\keyword等指令想要以繁體中文的方式來顯示，要怎麼處理？

**Comment by papayaistrash** [comment]
> #58

請問是要加在哪裡？我在overleaf上那樣操作並沒有變化。

**Comment by sikouhjw** [comment]
`\renewcommand{\keywords}`
https://github.com/ElegantLaTeX/ElegantPaper/blob/99bb48fcbdf46c06bb07a115e9464ecbf2955809/elegantpaper.cls#L198

**Comment by sikouhjw** [comment]
> 
> 
> > #58
> 
> 請問是要加在哪裡？我在overleaf上那樣操作並沒有變化。

```latex
\documentclass{elegantpaper}
\usepackage[fontset=ubuntu]{ctex}
\begin{document}
叡
\end{document}
```

**Comment by papayaistrash** [comment]
非常感謝！
