### ISSUE TITLE
關於腳註的型態

### ISSUE THREAD

**Issue by papayaistrash** [ElegantLaTeX/ElegantPaper#62]
想請問一下如何讓腳著在行內呈現出上標的型態呢？感謝

**Comment by sikouhjw** [comment]
```tex
\documentclass{elegantpaper}
\begin{document}
  test\footnote{test}
\end{document}
```

**Comment by papayaistrash** [comment]
我用了這種方法了，但在overleaf中，它呈現出來的腳註是會與文字一樣的大小，高度的。

**Comment by sikouhjw** [comment]
你为什么不提供更多的信息？
![图片](https://user-images.githubusercontent.com/49770925/124435329-78268780-dda7-11eb-821b-e3f6a3acd024.png)

**Comment by papayaistrash** [comment]
非常抱歉造成閣下的困擾。我忘了可以提供圖片
![截圖 2021-07-05 15 44 57](https://user-images.githubusercontent.com/70697738/124435831-f551fc80-dda7-11eb-8567-859fed994aa9.png)
在這張圖片中，我希望腳註13可以在文字中呈現出上標的形式（必须在中文模式下＾13）
請問要如何達成？
感謝

**Comment by sikouhjw** [comment]
给 MWE: https://zhuanlan.zhihu.com/p/94837029

**Comment by papayaistrash** [comment]
好，感謝
