### ISSUE TITLE
在lang=en模式下如果引用中文文献无法显示

### ISSUE THREAD

**Issue by randolfly** [ElegantLaTeX/ElegantPaper#63]
在英文环境下无法显示中文，是否可能独立添加参考文献来让中文文献正常显示？

问题如下图：
<img width="535" alt="屏幕截图 2021-10-13 212659" src="https://user-images.githubusercontent.com/37769048/137141838-a6461c4a-e79a-4158-98aa-18de840755ca.png">

其中文献[1]是一篇中文文献，其名字在英文环境下无法显示。

**Comment by sikouhjw** [comment]
`\usepackage[scheme = plain]{ctex}`

**Comment by randolfly** [comment]
> `\usepackage[scheme = plain]{ctex}`

@sikouhjw 这样我尝试过，用了ctex宏包后文档格式会乱，我不知道怎么重新定义格式。

<img width="743" alt="屏幕截图 2021-10-13 214140" src="https://user-images.githubusercontent.com/37769048/137144586-eb6ac9a8-5c11-4271-aa2e-b1f2553636a1.png">

**Comment by sikouhjw** [comment]
> 
> 
> > `\usepackage[scheme = plain]{ctex}`
> 
> @sikouhjw 这样我尝试过，用了ctex宏包后文档格式会乱，我不知道怎么重新定义格式。
> 
> <img alt="屏幕截图 2021-10-13 214140" width="743" src="https://user-images.githubusercontent.com/37769048/137144586-eb6ac9a8-5c11-4271-aa2e-b1f2553636a1.png">

哪里的格式乱了？

**Comment by randolfly** [comment]
> > > `\usepackage[scheme = plain]{ctex}`
> > 
> > 
> > @sikouhjw 这样我尝试过，用了ctex宏包后文档格式会乱，我不知道怎么重新定义格式。
> > <img alt="屏幕截图 2021-10-13 214140" width="743" src="https://user-images.githubusercontent.com/37769048/137144586-eb6ac9a8-5c11-4271-aa2e-b1f2553636a1.png">
> 
> 哪里的格式乱了？

哦是我表述错误了，我想说的是字体不同了，比如前面正文的英文字体都受到了影响。有办法只改动中文的字体格式吗？谢谢

**Comment by sikouhjw** [comment]
> 
> 
> > > > `\usepackage[scheme = plain]{ctex}`
> > > 
> > > 
> > > @sikouhjw 这样我尝试过，用了ctex宏包后文档格式会乱，我不知道怎么重新定义格式。
> > > <img alt="屏幕截图 2021-10-13 214140" width="743" src="https://user-images.githubusercontent.com/37769048/137144586-eb6ac9a8-5c11-4271-aa2e-b1f2553636a1.png">
> > 
> > 
> > 哪里的格式乱了？
> 
> 哦是我表述错误了，我想说的是字体不同了，比如前面正文的英文字体都受到了影响。有办法只改动中文的字体格式吗？谢谢

使用 `pdflatex`

**Comment by randolfly** [comment]
@sikouhjw 您能具体说明一下编译顺序吗？我直接使用pdflatex编译会报错：

```tex
Missing \endcsname inserted.
<to be read again> 
```
我尝试了使用`pdflatex`和`pdflatex->bibtex->pdflatex->pdflatex`

**Comment by sikouhjw** [comment]
> 
> 
> @sikouhjw 您能具体说明一下编译顺序吗？我直接使用pdflatex编译会报错：
> 
> ```
> Missing \endcsname inserted.
> <to be read again> 
> ```
> 
> 我尝试了使用`pdflatex`和`pdflatex->bibtex->pdflatex->pdflatex`

我用 `pdflatex` 不会报错。

建议您将参考文献翻译成英文。
