### ISSUE TITLE
示例文件中的命令错误

### ISSUE THREAD

**Issue by syvshc** [ElegantLaTeX/ElegantPaper#64]
https://github.com/ElegantLaTeX/ElegantPaper/blob/99bb48fcbdf46c06bb07a115e9464ecbf2955809/elegantpaper-cn.tex#L45
https://github.com/ElegantLaTeX/ElegantPaper/blob/99bb48fcbdf46c06bb07a115e9464ecbf2955809/elegantpaper-en.tex#L39

应改为 

```latex
\documentclass[cn]{elegantpaper}
```

**Comment by EthanDeng** [comment]
OK
