### ISSUE TITLE
如何写中英两个标题，十分感谢

### ISSUE THREAD

**Issue by xxhe504** [ElegantLaTeX/ElegantPaper#65]
中文论文通常要求写英文的标题和摘，我不会写，麻烦问一下如何实现？请求出个双标题模板，捐款感谢

**Comment by MIngPAPA** [comment]
https://github.com/ElegantLaTeX/ElegantPaper/issues/23#issuecomment-608998866

**Comment by starxchina** [comment]
+1, 期望作者能添加一下, 感谢
