### ISSUE TITLE
添加多语言的代码块着色

### ISSUE THREAD

**Issue by MrZLeo** [ElegantLaTeX/ElegantPaper#66]
希望能提供常用的代码类型如C、C++、Java、Python等的着色，目测应该需要修改配置文件，但是没找到关键词着色在哪里设置。如果可以的话希望能提供一个简单的指南，我愿意帮助添加这个功能。

**Comment by sikouhjw** [comment]
1. ElegantLaTeX 系列无限期停更；
2. 您需要去看 `listings`、`minted` 宏包。
