### ISSUE TITLE
更新newtx宏包到1.702版本后elegant文档类无法使用

### ISSUE THREAD

**Issue by curiosusJR** [ElegantLaTeX/ElegantPaper#67]
错误提示：
> Undefined control sequence.
> <argument> ... \fi \fi \ifntxotf \ntx@origotftrue 
[{
	"resource": "/usr/local/texlive/2021/texmf-dist/tex/latex/newtx/newtxtext.sty",
	"owner": "LaTeX",
	"severity": 8,
	"message": "Undefined control sequence.\n<argument> ... \\fi \\fi \\ifntxotf \\ntx@origotftrue \n",
	"source": "LaTeX",
	"startLineNumber": 52,
	"startColumn": 1,
	"endLineNumber": 52,
	"endColumn": 65536
}]

通过重新安装旧版本texlive可以解决这个问题，elegant是我很喜爱的模板，希望可以兼容新版本。

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantBook/issues/175
