### ISSUE TITLE
运行报错显示CLS文件Missing \begin{document}. <

### ISSUE THREAD

**Issue by rockycos** [ElegantLaTeX/ElegantPaper#7]
直接运行模板就显示CLS文件出错，显示Missing \begin{document}. <以及一系列错误，请各位指点一二。
[log.txt](https://github.com/ElegantLaTeX/ElegantPaper/files/3099677/log.txt)

**Comment by EthanDeng** [comment]
请保证你的代码是 UTF8 编码，请安装完整版 TeX Live 进行编译。你的报错信息里面还有 `$` 符号的问题，请确认你的数学公式没有错误（可以使用我们提供的最小示例进行测试）。
