### ISSUE TITLE
authoryear格式参考文献在文中显示时无法显示全部作者

### ISSUE THREAD

**Issue by Daron511** [ElegantLaTeX/ElegantPaper#72]
请问，如果我想文中的参考文献中显示全部作者的姓氏，而不是用et al.表示，需要输入什么命令？
我在网上搜到的是使用\citet*{}，但在这个模板下似乎是无效的。
谢谢！

**Comment by sikouhjw** [comment]
模板用的是 `biblatex-gb7714-2015` 宏包，不支持你说的显示全部作者的效果，可以向 `biblatex-gb7714-2015` 提 issue。
