### ISSUE TITLE
请问这个模板是不支持citet和citep吗，我这边直接报错了

### ISSUE THREAD

**Issue by ManlioWu** [ElegantLaTeX/ElegantPaper#73]

**Comment by EthanDeng** [comment]
群中已经回复过，由于这两个命令是 `natbib` 里面的，在引用 biblatex 包的时候，默认不加载 `natbib=true` 选项。
一个更加简单的方法是：使用 `\textcite` 代替 `\citet`，使用 `\parencite` 代替 `\citep`。

> Use \textcite instead of \citet, \parencite instead of \citep. Alternatively, you may keep on using \citet and \citep if you add natbib=true to the loading options.

**参考**：[https://tex.stackexchange.com/questions/427970/how-do-i-transition-from-natbib-to-biblatex](https://tex.stackexchange.com/questions/427970/how-do-i-transition-from-natbib-to-biblatex)
