### ISSUE TITLE
无法打印参考文献

### ISSUE THREAD

**Issue by Lailaps2000** [ElegantLaTeX/ElegantPaper#76]
在将参考文献输入到reference.bib后发现无法打印参考文献。控制台提示的错误包括：
LaTeX Warning: Citation 'lucas1878theorie' on page 6 undefined on input line 210.
LaTeX Warning: Empty bibliography on input line 352.
LaTeX Warning: There were undefined references.
在本地编译范例文件也遭遇了相同问题，重新安装elegantpaper未能解决问题
排版选项使用的是Xelatex+MakeIndex+Bibtex，所有宏包均已更新到最新
Texwork版本为0.6.7(Miktex 22.3)

**Comment by EthanDeng** [comment]
你的模板是新版的？请用最新版的模板，另外提供你的示例代码。

**Comment by Lailaps2000** [comment]
感谢您的回复，刚刚已经解决了这个问题。需要在开头的 documentclass 里向 backend 传入 bibtex 这个参数
```tex
\documentclass[backend=bibtex]{elegantpaper}
```
不过文档里写的
```tex
\documentclass[bibend=bibtex]{elegantpaper}
```
似乎并不能把 biber 切换成 bibtex

**Comment by Zhuohao-Li** [comment]
> 

可以提供一下示例代码嘛，我也碰到了这个问题

**Comment by Lailaps2000** [comment]
> > 
> 
> 可以提供一下示例代码嘛，我也碰到了这个问题

抱歉之前没看到……下面是自己的示例代码
关键是要在 documentclass里面传入 `backend=bibtex` 这个参数

```latex
\documentclass[lang=cn,11pt,citestyle=gb7714-2015, bibstyle=gb7714-2015,backend=bibtex]{elegantpaper}

\title{blbl}
\author{blbl}
\institute{blbl}
\date{}

% 需要的宏包可以自行调用
%\usepackage{fancyvrb}
%\usepackage{amssymb}
\usepackage{amsfonts}
\usepackage{mathrsfs}

\begin{document}

\maketitle

\begin{abstract}
blbl
\end{abstract}

\tableofcontents

\section{blbl}
\cite{blbl}

\newpage
\nocite{*}
\printbibliography
\end{document}
```

**Comment by hushidong** [comment]
要用gb7714-2015，那么backend应改成biber，且用biber编译文献。
用bibtex虽然不会出错，但很多功能就失去了。

latex文档是多步编译的，所以所谓参考文献无法生成大多数是中间步参考文献编译时出错或者就没有做。

测试到底有没有问题最简单的方法就是用命令行进行3步编译看到底是否存在问题:
```
xelatex jobname
biber jobname
xelatex jobname
```
