### ISSUE TITLE
如何将中文标点全部改为西文标点？

### ISSUE THREAD

**Issue by ZRJerry-z** [ElegantLaTeX/ElegantPaper#81]
公式和中文混杂输入的时候，一并使用西文标点比较妥当。然而一直切换全半角不甚方便，有没有方法可使输入的中文标点全部编译为西文标点呢？
查询到 XeCJK 宏包里有 \punctstyle{banjiao} 这样的处理方式，然而应用于此似乎没有效果.

**Comment by xkwxdyy** [comment]
`\punctstyle{banjiao}` 只是改变了标点的编译出来的前后间距，但是本身是西文还是中文并没有改变。
估计真要全换，可以仿照 `mapping`  把“。”映射为“.”的那个原理，把其它也映射掉。

**Comment by ZRJerry-z** [comment]
> `\punctstyle{banjiao}` 只是改变了标点的编译出来的前后间距，但是本身是西文还是中文并没有改变。 估计真要全换，可以仿照 `mapping` 把“。”映射为“.”的那个原理，把其它也映射掉。

感谢。试着操作了一下，在这个模版下操作仍有一些小问题: 
(1) 使用 `\punctstyle{banjiao}` 不仅没有改变中西文，也没有改变间距。
(2) 此模版下如何妥当地使用 `mapping` 呢？直接导言区使用好像不太行(´Д`). 目前只想到用自定义字体的方法去操作，然而这样可能略复杂了？有没有在 cls 文件里修改的方法. 
(3) 我拙劣地使用自定义字体的方法, 用 `mapping` 改变了句号，发现虽然是变化成功了，可编译出来二者的高度却不一致。
是否有解决上述问题的办法呢？

**Comment by ZRJerry-z** [comment]
> `\punctstyle{banjiao}` 只是改变了标点的编译出来的前后间距，但是本身是西文还是中文并没有改变。 估计真要全换，可以仿照 `mapping` 把“。”映射为“.”的那个原理，把其它也映射掉。

感谢。试着操作了一下，在这个模版下操作仍有一些小问题:
(1) 使用 \punctstyle{banjiao} 不仅没有改变中西文，也没有改变间距。
(2) 此模版下如何妥当地使用 `mapping` 呢？直接导言区使用好像不太行('Д'). 目前只想到用自定义字体的方法去操作，然而这样可能略复杂了？有没有在 cls 文件里修改的方法. (3) 我拙劣地使用自定义字体的方法, 用 `mapping` 改变了句号，发现虽然是变化成功了，可编译出来二者的高度却不一致。
是否有解决上述问题的办法呢？

**Comment by xkwxdyy** [comment]
> > `\punctstyle{banjiao}` 只是改变了标点的编译出来的前后间距，但是本身是西文还是中文并没有改变。 估计真要全换，可以仿照 `mapping` 把“。”映射为“.”的那个原理，把其它也映射掉。
> 
> 感谢。试着操作了一下，在这个模版下操作仍有一些小问题: (1) 使用 \punctstyle{banjiao} 不仅没有改变中西文，也没有改变间距。 (2) 此模版下如何妥当地使用 `mapping` 呢？直接导言区使用好像不太行('Д'). 目前只想到用自定义字体的方法去操作，然而这样可能略复杂了？有没有在 cls 文件里修改的方法. (3) 我拙劣地使用自定义字体的方法, 用 `mapping` 改变了句号，发现虽然是变化成功了，可编译出来二者的高度却不一致。 是否有解决上述问题的办法呢？

可以参考一下这个
https://www.zhihu.com/question/531128455/answer/2469830739

**Comment by ZRJerry-z** [comment]
妙！
