### ISSUE TITLE
在使用中文模板编译过程中无法成功编译出参考文献

### ISSUE THREAD

**Issue by LnmForGit** [ElegantLaTeX/ElegantPaper#82]
在使用中文模板编译过程中无法成功编译出参考文献，编译时提示参考文献未定义。
![image](https://user-images.githubusercontent.com/37356600/174931358-3d39a307-b7aa-4dd2-a667-10048780a76a.png)
![image](https://user-images.githubusercontent.com/37356600/174931406-c69b76d5-429e-4e30-a806-2e44086ba91f.png)

**Comment by xkwxdyy** [comment]
什么编译方式，`.bib` 文件里有内容吗，有正确地 `add` 相关 `.bib` 文件吗

**Comment by LnmForGit** [comment]
使用了xelatex -> biber/bibtex -> xelatex -> xelatex方式编译，主要问题应该是没有成功引入相关 .bib 文件，能请教一下如何引用bib文件吗。

**Comment by xkwxdyy** [comment]
> 使用了xelatex -> biber/bibtex -> xelatex -> xelatex方式编译

`biber` 和 `bibtex` 是两种不同的编译方式，如何引用请查阅 elegant 相关手册，一定有讲。

**Comment by xkwxdyy** [comment]
我刚看了一下手册，并没有对 `bib` 文件的引用接口改动，这样的话去读 `lshort-zh-cn` 参考文献部分。

**Comment by LnmForGit** [comment]
好的，我去看一下，谢谢

**Comment by xiaoffffff** [comment]
我这里也是编译不出文献，用的最新版，报错
![image](https://user-images.githubusercontent.com/100138930/203691588-0a119c71-4e49-4ceb-9f51-28f4e1939c27.png)

**Comment by sikouhjw** [comment]
> 我这里也是编译不出文献，用的最新版，报错 ![image](https://user-images.githubusercontent.com/100138930/203691588-0a119c71-4e49-4ceb-9f51-28f4e1939c27.png)

请你使用 `biber`，https://github.com/ElegantLaTeX/ElegantBook/issues/217

**Comment by xiaoffffff** [comment]
> > 我这里也是编译不出文献，用的最新版，报错 ![图像](https://user-images.githubusercontent.com/100138930/203691588-0a119c71-4e49-4ceb-9f51-28f4e1939c27.png)
> 
> 请你使用 ，[ElegantLaTeX/ElegantBook#217](https://github.com/ElegantLaTeX/ElegantBook/issues/217)`biber`

嗯嗯，谢谢，我试一下

**Comment by murenzzj** [comment]
请问问题解决了吗，我这里使用biber或者bibtex都无法编译成功，不知道是什么原因
