### ISSUE TITLE
正文如何段间距？

### ISSUE THREAD

**Issue by gouff** [ElegantLaTeX/ElegantPaper#84]
目前正文的段间距是默认的行间距，我想在每段之间增加段间距，应该如何设置？
如果单纯设置\setlength{\parskip}{x em}，这样会影响全局段间距，而不是只影响正文。

**Comment by sikouhjw** [comment]
- 工作 Paper 不需要在意格式；
- 如果你想说的是章节不需要段间距，可以自行设置。

**Comment by gouff** [comment]
可否考虑增加这个功能？每段自行设置比较麻烦，不够简约。

**Comment by sikouhjw** [comment]
在导言区设置不就全局生效了？不需要每段设置。

**Comment by gouff** [comment]
导言区设置会影响section标题和正文之间的间距！

**Comment by gouff** [comment]
我想要的效果是，保持section和正文的段间距不变，只是正文的段落之间控制间距

**Comment by sikouhjw** [comment]
所以我说了可以自行设置，模板没有提供这个功能，在目的上也不需要提供这个功能，工作论文不需要在意格式。
