### ISSUE TITLE
请问怎么修改章节标题的序号和内容的字体大小呢？

### ISSUE THREAD

**Issue by xiaoffffff** [ElegantLaTeX/ElegantPaper#85]
请问每个section的序号和标题内容怎么修改大小呢？
1 引言 %%目前是小三号字，怎么让其变成小四号呢？

**Comment by sikouhjw** [comment]
- 不支持修改；
- 工作 paper 不需要在意格式；
- 如果在意格式说明你需要的不是 ElegantPaper。

**Comment by xiaoffffff** [comment]
哈哈，谢谢
