### ISSUE TITLE
如何调整正文，目录，摘要的字号

### ISSUE THREAD

**Issue by songXuezhaiprimer** [ElegantLaTeX/ElegantPaper#86]
你好，这个模板非常有帮助，不过我需要调整正文，目录以及摘要的字号，以符合校方的规定，请问应该怎么设置？谢谢

**Comment by xkwxdyy** [comment]
你想用于学位论文？恐怕这个模版并不合适

**Comment by songXuezhaiprimer** [comment]
并不是学位论文，是一个小组作业的报告

**Comment by songXuezhaiprimer** [comment]
老师对字号有要求，最好调整到老师的要求

**Comment by EthanDeng** [comment]
这个模板继承了 latex 默认的字体大小，全文字体选项只有 10pt，11pt，12pt。

1.  如果你要更改局部字体大小的话，可以使用 \large，\small 这种相对字体的命令；
2. 如果想要全局修改字体的大小的话，可以使用 [extsizes](https://ctan.org/pkg/extsizes) 宏包更改字体；
3. 如果要五号这种字号，建议再次调用 ctex 宏包，对字体进行设定。

**Comment by yinxiuqu** [comment]
> 这个模板继承了 latex 默认的字体大小，全文字体选项只有 10pt，11pt，12pt。
> 
>     1. 如果你要更改局部字体大小的话，可以使用 \large，\small 这种相对字体的命令；
> 
>     2. 如果想要全局修改字体的大小的话，可以使用 [extsizes](https://ctan.org/pkg/extsizes) 宏包更改字体；
> 
>     3. 如果要五号这种字号，建议再次调用 ctex 宏包，对字体进行设定。

再次\usepackage{ctex}之后，再\ctexset{}，似乎设置的内容都不起作用了。

**Comment by sikouhjw** [comment]
> 再次\usepackage{ctex}之后，再\ctexset{}，似乎设置的内容都不起作用了。

不支持 `\ctexset`

**Comment by sikouhjw** [comment]
> 你好，这个模板非常有帮助，不过我需要调整正文，目录以及摘要的字号，以符合校方的规定，请问应该怎么设置？谢谢

不建议使用该模板用来写小组作业，建议用 `ctexart`。
