### ISSUE TITLE
如何让某一段不缩进，试了\noindent没用

### ISSUE THREAD

**Issue by Jie-Qiao** [ElegantLaTeX/ElegantPaper#87]
用 `\noindent` 提示 `Undefined control sequence`.

**Comment by EthanDeng** [comment]
我这边测试没问题啊，提供你的代码吧。

**Comment by Jie-Qiao** [comment]
> 我这边测试没问题啊，提供你的代码吧。

我刚看了下，原来输完\noindent后面跟了中文，忘记加空格了，加空格就可以了。
