### ISSUE TITLE
Index Making

### ISSUE THREAD

**Issue by YifengMa9** [ElegantLaTeX/ElegantPaper#9]
Has anyone tried to generate index in this template? I tried but it did not work. My code is shown below.

```LaTex
\documentclass[lang=cn]{elegantpaper}
\usepackage{makeidx}
\makeindex



% title information
\title{A Working Paper Example}
\author{ddswhu} 
\institute{Elegant\LaTeX{} Group}
\version{1.00}
\date{\today}

\begin{document}

\maketitle

\section{勾股定理}
% 第 1 页
勾股定理在西方称为毕达哥拉斯定理（Pythagoras' theorem）。
\index{Pythagoras}
% ...
% 第 2 页
在中国常称勾股定理为商高定理。\index{商高}

\printindex
\end{document}
```

Index can be generated when using \documentclass{ctexart} with the same code.

**Comment by onns** [comment]
Try `\usepackage{imakeidx}`

**Comment by YifengMa9** [comment]
Problem is solved by using the typeset recommended by the TexPad (and change pdfLaTex to XeLaTex) for now... 
Sorry to bother you.
