### ISSUE TITLE
希望能手动指定BIB文件路径和文件名

### ISSUE THREAD

**Issue by ehehela** [ElegantLaTeX/ElegantPaper#92]
建议出一个选项，默认使用reference.bib文件，若该选项选中，则使用用户定义的BIB文件路径和名称。

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantPaper/blob/d8e407917e49cf98619405fa7cd0660f92a99a58/elegantpaper-cn.tex#L16

**Comment by hjnnjh** [comment]
这个project停止维护了，可惜
